<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>a91290e7-554d-4681-aeef-adb9ae61dba0</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Socializer.Domain\Socializer.Domain.csproj" />
      <ProjectReference Include="..\Socializer.Application\Socializer.Application.csproj" />
      <ProjectReference Include="..\Socializer.Infrastructure\Socializer.Infrastructure.csproj" />
      <ProjectReference Include="..\Socializer.Contracts\Socializer.Contracts.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
      <PackageReference Include="Serilog.Sinks.Seq" Version="9.1.0" />
      <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    </ItemGroup>

</Project>
